// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pvayutvfdssokthelyis.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB2YXl1dHZmZHNzb2t0aGVseWlzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEzODg5NjUsImV4cCI6MjA1Njk2NDk2NX0.QADWwaKuKejdZkYl6zr9T3ROsfV1-TLaBiwCs5vLg_k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);